GET https://lqwxjiijnhefterkeety.supabase.co/rest/v1/compounds
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxd3hqaWlqbmhlZnRlcmtlZXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY1OTU5NzksImV4cCI6MjA0MjE3MTk3OX0.Vow361AN7JG8uD0NK5MGuAVwrdwhm9oE0tt8WLjwETo
Content-Type: application/json
